# Generated by Django 4.1.3 on 2022-11-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterTicket',
            fields=[
                ('theater_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'movie_theater_tickets',
            },
        ),
    ]
